language: php

php:
  - 7.2
  - 7.3
  - 7.4

matrix:
  fast_finish: true

before_script:
  - composer self-update
  - composer install --dev --no-interaction

script:
  - ./vendor/bin/phpunit --verbose
  - ./vendor/bin/phpcs src --standard=psr2 -sp