language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer install --dev --no-interaction

script:
  - ./vendor/bin/phpunit --verbose
  - ./vendor/bin/phpcs src --standard=psr2 -sp